### ISSUE TITLE
EPIC: KPIs

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/subgraph#41]
## Problem
We need to start measuring some KPIs to understand how developers are using OPENFORMAT.

## Tasklist
- [ ] Measure number of subgraph calls (time based)
- [ ] [Measure Unique wallets](https://github.com/open-format/subgraph/issues/39)
- [ ] https://github.com/open-format/subgraph/issues/40
- [ ] [Gas estimations](https://github.com/open-format/contracts/issues/111)
